"""cascade delete invoices

Revision ID: 07086aa8ed73
Revises: 5f75348f46cf
Create Date: 2026-03-29 17:44:40.466180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07086aa8ed73'
down_revision: Union[str, Sequence[str], None] = '5f75348f46cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_seller_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.add_column('shops', sa.Column('domain', sa.String(length=63), nullable=True))
    op.alter_column('shops', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index(op.f('ix_shops_custom_domain'), table_name='shops')
    op.drop_index(op.f('ix_shops_subdomain'), table_name='shops')
    op.create_index(op.f('ix_shops_domain'), 'shops', ['domain'], unique=True)
    op.drop_column('shops', 'custom_domain')
    op.drop_column('shops', 'subdomain')
    op.drop_column('shops', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('subdomain', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('custom_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shops_domain'), table_name='shops')
    op.create_index(op.f('ix_shops_subdomain'), 'shops', ['subdomain'], unique=True)
    op.create_index(op.f('ix_shops_custom_domain'), 'shops', ['custom_domain'], unique=True)
    op.alter_column('shops', 'description',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_column('shops', 'domain')
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_seller_id_fkey'), 'invoices', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###
