"""update shop models

Revision ID: 0fbe3c471895
Revises: 0cffbdbbb4e2
Create Date: 2026-03-24 20:22:03.602741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbe3c471895'
down_revision: Union[str, Sequence[str], None] = '0cffbdbbb4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_seller_id'), table_name='shops')
    op.create_index(op.f('ix_shops_seller_id'), 'shops', ['seller_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_seller_id'), table_name='shops')
    op.create_index(op.f('ix_shops_seller_id'), 'shops', ['seller_id'], unique=False)
    # ### end Alembic commands ###
