"""update shop models

Revision ID: 152fd5b935bf
Revises: 0fbe3c471895
Create Date: 2026-03-26 20:03:13.893312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152fd5b935bf'
down_revision: Union[str, Sequence[str], None] = '0fbe3c471895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('description', sa.String(length=512), nullable=True))
    op.add_column('shops', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('shops', sa.Column('number', sa.String(length=20), nullable=True))
    op.alter_column('shops', 'subdomain',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'subdomain',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.drop_column('shops', 'number')
    op.drop_column('shops', 'email')
    op.drop_column('shops', 'description')
    # ### end Alembic commands ###
