"""update shop models

Revision ID: 5f75348f46cf
Revises: 152fd5b935bf
Create Date: 2026-03-26 20:20:58.624871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f75348f46cf'
down_revision: Union[str, Sequence[str], None] = '152fd5b935bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
