"""update models

Revision ID: e702e8a1b299
Revises: 33b156a9a336
Create Date: 2026-04-01 17:54:05.042061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e702e8a1b299'
down_revision: Union[str, Sequence[str], None] = '33b156a9a336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_shop_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('shops_seller_id_fkey'), 'shops', type_='foreignkey')
    op.create_foreign_key(None, 'shops', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.create_foreign_key(op.f('shops_seller_id_fkey'), 'shops', 'sellers', ['seller_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_shop_id_fkey'), 'products', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###
